_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "D:/UserD/Li/FSCE-1/checkpoints/mydataset_dla60/baseline/step2_ablation/SIZES+RATIOS_28.341/model_0054999.pth"
#  PIXEL_MEAN: [60., 60., 60.]
  MASK_ON: False

#  RESNETS:
#    DEPTH: 50
#  BACKBONE:
#    NAME: build_resnet_fpn_backbone
#    FREEZE: False
#    FREEZE_AT: 5
#    FREEZE_P5: False
#  FPN:
#    IN_FEATURES:
#      - res2
#      - res3
#      - res4
#      - res5
  DLA:
    ARCH: "DLA-60"
  BACKBONE:
    NAME: build_dla_fpn_backbone
    FREEZE: False
    FREEZE_AT: 5
    FREEZE_P5: False
  FPN:
    IN_FEATURES:
    - level2
    - level3
    - level4
    - level5

  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256 # 1
    NUM_CLASSES: 5
    FREEZE_FEAT: False
    FOCAL_ALPHA: 1.
    FOCAL_GAMMA: 2.
#    IN_FEATURES:
#    - level5
  ANCHOR_GENERATOR:
#    SIZES: [[39, 158, 271, 350, 433]]   # _before
#    ASPECT_RATIOS:  [[1.7, 5.3, 5.6]]   # _before
    SIZES: [[23.8, 78.8, 135.6, 195.2, 260]]
    ASPECT_RATIOS: [[1.05, 6.1, 13]]
  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
#    IN_FEATURES:
#    - level5
    POST_NMS_TOPK_TRAIN: 4000 # 2
    FOCAL_ALPHA: 0.25
    FOCAL_GAMMA: 2.
DATASETS:
  TRAIN: ('custom1_train',)
  TEST: ('custom1_val',)
#  TRAIN: ('custom1_train_before',)
#  TEST: ('custom1_val_before',)
SOLVER:
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  IMS_PER_BATCH: 4

  STEPS: (60000, 85000, 110000)
  CHECKPOINT_PERIOD: 5000
  MAX_ITER: 150000
  WARMUP_ITERS: 2000
  BASE_LR: 0.005
INPUT:
  USE_TRANSFORM_AUG: True
  USE_MIXUP: True
  USE_MOSAIC: False
  MOSAIC_BATCH: 4
  CROP:
    ENABLED: False
OUTPUT_DIR: "D:/UserD/Li/FSCE-1/checkpoints/mydataset_dla60/baseline/step3_ablation/SIZES+RATIOS+MIXUP+UNNORM"

TEST:
  EVAL_PERIOD: 5000