_BASE_: "D:/UserD/Li/FSCE-1/configs/Base-RCNN-FPN.yaml"

MODEL:
  MASK_ON: False
  WEIGHTS: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/50-shot/R_101_FPN_before_ft_all/model_reset_combine.pth"
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 4000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 5
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256 # do increased positive fraction help? Yes, it does.

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      DECAY:
        ENABLED: True
        STEPS: [ 6000, 10000 ]
        RATE: 0.5
      IOU_THRESHOLD: 0.8  # high credibility proposals provide consistency
      REWEIGHT_FUNC: exp

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  USE_TRANSFORM_AUG: True
#  CROP:
#    ENABLED: True


DATASETS:
  TRAIN: ('custom1_trainval_all_50shot',)
  TEST: ('custom1_val_novel',)

SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.001
  GAMMA: 0.3
  STEPS: (20000,)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 5000

OUTPUT_DIR: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/50-shot/R_101_FPN_ft_all"