_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/50-shot/R_101_FPN_ft_novel/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256 # 1
    NUM_CLASSES: 5
    FREEZE_FEAT: False
  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5
    FREEZE_P5: False
  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 4000 # 2
INPUT:
  USE_TRANSFORM_AUG: True
DATASETS:
  TRAIN: ('custom1_trainval_all_50shot',)
  TEST: ('custom1_val_novel',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (10000,)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 1000
OUTPUT_DIR: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/50-shot/R_101_FPN_ft_novel"