_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/baseline/R_101_FPN_baseline/model_log2.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5
    FREEZE_P5: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256 # 1
    NUM_CLASSES: 5
    FREEZE_FEAT: False
    FOCAL_ALPHA: 1.
    FOCAL_GAMMA: 2.

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 4000 # 2
    FOCAL_ALPHA: 0.5
    FOCAL_GAMMA: 0.5
DATASETS:
  TRAIN: ('custom1_train',)
  TEST: ('custom1_val',)
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  IMS_PER_BATCH: 8
  STEPS: (10000, )
  CHECKPOINT_PERIOD: 5000
  MAX_ITER: 20000
  WARMUP_ITERS: 2000
  BASE_LR: 0.001
INPUT:
  USE_TRANSFORM_AUG: True
  CROP:
    ENABLED: False
OUTPUT_DIR: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/baseline/R_101_FPN_baseline"
TEST:
  EVAL_PERIOD: 5000