_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/baseline_555/SIZES+RATIOS/model_0114999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    NAME: build_resnet_fpn_backbone
    FREEZE: False
    FREEZE_AT: 5
    FREEZE_P5: False
  FPN:
    IN_FEATURES:
      - res2
      - res3
      - res4
      - res5

  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256 # 1
    NUM_CLASSES: 5
    FREEZE_FEAT: False
    FOCAL_ALPHA: 1.
    FOCAL_GAMMA: 2.
  ANCHOR_GENERATOR:
#    SIZES: [[23.8, 78.8, 135.6, 195.2, 260]]
#    ASPECT_RATIOS: [[1.05, 6.1, 13]]
    SIZES: [[23, 75.7, 126.8, 177, 242.9]]    # 555
    ASPECT_RATIOS: [[0.21, 1.7, 12.3]]      # 555
#    SIZES: [[39, 158, 271, 350, 433]]   # _before
#    ASPECT_RATIOS:  [[1.7, 5.3, 5.6]]   # _before

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000 # 2
    FOCAL_ALPHA: 0.25
    FOCAL_GAMMA: 2.
DATASETS:
#  TRAIN: ('custom1_train',)
#  TEST: ('custom1_val',)
  TRAIN: ('custom1_train_555',)
  TEST: ('custom1_val_555',)
#  TRAIN: ('custom1_train_before',)
#  TEST: ('custom1_val_before',)
SOLVER:
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  IMS_PER_BATCH: 4

  STEPS: (60000, 85000, 110000)
  CHECKPOINT_PERIOD: 5000
  MAX_ITER: 150000
  WARMUP_ITERS: 0
  BASE_LR: 0.005
INPUT:
  USE_TRANSFORM_AUG: True
  USE_MIXUP: False
  USE_MOSAIC: False
  MOSAIC_BATCH: 4
  CROP:
    ENABLED: False
OUTPUT_DIR: "D:/UserD/Li/FSCE-1/checkpoints/mydataset/baseline_555/SIZES+RATIOS"
TEST:
  EVAL_PERIOD: 5000