_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "D:/UserD/Li/FSCE-1/checkpoints/coco/model_final.pth"
  PIXEL_MEAN: [60.703, 60.708, 60.708]
  MASK_ON: False
  DLA:
    ARCH: DLA-34
  BACKBONE:
    NAME: build_dla_fpn_backbone
    FREEZE: False
    FREEZE_AT: 5
    FREEZE_P5: False
  FPN:
    IN_FEATURES:
    - level2
    - level3
    - level4
    - level5
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256 # 1
    NUM_CLASSES: 5
    FREEZE_FEAT: False
    FOCAL_ALPHA: 1.
    FOCAL_GAMMA: 2.
  ANCHOR_GENERATOR:
    SIZES: [ [ 39, 158, 271, 350, 433 ] ]   # _before
    ASPECT_RATIOS: [ [ 1.7, 5.3, 5.6 ] ]   # _before
  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 4000 # 2
    FOCAL_ALPHA: 0.25
    FOCAL_GAMMA: 2.
DATASETS:
  TRAIN: ('custom1_train_before',)
  TEST: ('custom1_val_before',)
SOLVER:
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  IMS_PER_BATCH: 4
  STEPS: (70000, 80000)
  CHECKPOINT_PERIOD: 5000
  MAX_ITER: 90000
  WARMUP_ITERS: 2000
  BASE_LR: 0.005
INPUT:
  USE_TRANSFORM_AUG: True
  CROP:
    ENABLED: False
OUTPUT_DIR: "D:/UserD/Li/FSCE-1/checkpoints/mydataset_dla34/baseline/DLA_34_FPN_baseline"
TEST:
  EVAL_PERIOD: 5000